replicaCount: 1

image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "1.37.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
